### ISSUE TITLE
iOS got error when displaying contacts

### ISSUE THREAD

**Issue by cindyha** [AhsanAyaz/flutter_contacts_list#3]
Hi again!
I'm just a newbie learning flutter. So try to run the code on ios device also and see this error:

![952AF150-47FA-4DF2-9348-56F655492CDF](https://user-images.githubusercontent.com/5300207/80583514-9872ed80-8a10-11ea-9336-77171866e120.jpg)

**Comment by zebpay-peswani** [comment]
Hi I got the same error. You can solve this error by simply putting a check if your displayName is null or not also your phones is not empty and null like below
```
if (contact == null ||
            contact.displayName == null ||
            contact.phones == null ||
            contact.phones.length == 0) {
          return false;
        }
```

**Comment by AhsanAyaz** [comment]
@cindyha can you try and confirm if @zebpay-peswani's works for you?
